#!/usr/bin/env python3
"""Derived local network observations for the learning fixtures.

The evaluator has two deliberately separate inputs: effective control state
from the local controller, and a request plus raw path trace from a separate
traffic/device model. The trace contains mechanism facts, never an expected
result or health flag. Vendor requests in this repository remain illustrative;
the output is bounded local-emulator evidence.
"""

from __future__ import annotations

import copy
from typing import Any


FORBIDDEN_INPUT_KEYS = {
    "mechanism" + "_fault", "fault" + "_plane", "expected_result",
    "expected_failure", "probe" + "_healthy",
}


def _assert_raw(value: Any) -> None:
    if isinstance(value, dict):
        for key, child in value.items():
            if key in FORBIDDEN_INPUT_KEYS:
                raise ValueError(f"derived evaluator input cannot contain {key}")
            _assert_raw(child)
    elif isinstance(value, list):
        for child in value:
            _assert_raw(child)


def _result(healthy: bool, failure: str, observations: dict[str, Any], trace: dict[str, Any]) -> dict[str, Any]:
    return {
        "healthy": bool(healthy),
        "result": "HEALTHY" if healthy else failure,
        "observations": observations,
        "derivation": "computed from effective controller fields and raw path trace; no expected outcome input",
        "trace_id": trace["trace_id"],
    }


def derive_dataplane(module: str, control: dict[str, Any], traffic_request: dict[str, Any], path_trace: dict[str, Any]) -> dict[str, Any]:
    """Compute a mechanism-specific result from raw request and path facts.

    There is intentionally no named-failure parameter. ``path_trace`` is
    generated by the local device/service model and carries raw states such as
    ``carrier_state`` or ``underlay_reachability``. This function computes the
    outcome from those states rather than accepting a caller-supplied outcome.
    """
    _assert_raw(control)
    _assert_raw(traffic_request)
    _assert_raw(path_trace)
    trace = path_trace["device_service_state"]

    if module == "01":
        interfaces = control["interfaces"]
        carrier = trace["carrier_state"] == "UP"
        path_mtu = min(interfaces["a"]["mtu"], interfaces["b"]["mtu"])
        packet_size = traffic_request["packet_size"]
        return _result(carrier and packet_size <= path_mtu, "MTU_MISMATCH", {
            "path_mtu": path_mtu, "packet_size": packet_size, "carrier": carrier,
            "carrier_state": trace["carrier_state"],
        }, path_trace)

    if module == "02":
        frame = traffic_request["frame"]
        allowed = control["switch"]["trunk_allowed"]
        admitted = (trace["tag_transit_state"] == "ADMITTED"
                    and frame["vlan"] in allowed
                    and control["switch"]["access_vlan"] == frame["vlan"]
                    and control["gateway_vlan"] == frame["gateway_vlan"])
        return _result(admitted, "VLAN_TAG_DROPPED", {
            "vlan": frame["vlan"], "trunk_allowed": copy.deepcopy(allowed),
            "access_vlan": control["switch"]["access_vlan"],
            "gateway_vlan": control["gateway_vlan"], "hop_admission": admitted,
            "tag_transit_state": trace["tag_transit_state"],
        }, path_trace)

    if module == "03":
        blocked = list(control["blocked_edges"])
        cycle = traffic_request["cycle_possible"] and (not blocked or trace["loop_guard_state"] == "OPEN")
        healthy = bool(control["root"]) and bool(blocked) and not cycle and control["bundle_members"] >= 1
        return _result(healthy, "STP_LOOP_DETECTED", {
            "root": control["root"], "blocked_edges": blocked,
            "cycle_detected": cycle, "bundle_members": control["bundle_members"],
            "loop_guard_state": trace["loop_guard_state"],
        }, path_trace)

    if module == "04":
        flow = traffic_request["flow"]
        rule = control["nat_rule"]
        translation = None
        if rule != "disabled" and trace["nat_table_state"] == "POPULATED" and flow["inside"] in traffic_request["available_translations"]:
            translation = traffic_request["available_translations"][flow["inside"]]
        neighbor = traffic_request["ipv6_neighbor_state"]
        healthy = bool(translation) and neighbor == "REACHABLE" and control["nd"] == "enabled"
        return _result(healthy, "NAT_TRANSLATION_MISSING", {
            "inside": flow["inside"], "translation": translation,
            "ipv6_neighbor_state": neighbor, "nat_rule": rule,
            "nat_table_state": trace["nat_table_state"],
        }, path_trace)

    if module == "05":
        area_ok = control["area"] == 0
        transport_up = trace["adjacency_transport"] == "UP"
        neighbor = traffic_request["neighbor_state"] if area_ok and transport_up else "DOWN"
        route = traffic_request["route_table"].get("10.5.0.0/16") if neighbor == "FULL" else None
        healthy = area_ok and control["network_type"] == traffic_request["network_type"] and neighbor == "FULL" and route == control["vrf"]
        return _result(healthy, "OSPF_AREA_MISMATCH", {
            "area": control["area"], "network_type": control["network_type"],
            "neighbor_state": neighbor, "route": route, "vrf": control["vrf"],
            "adjacency_transport": trace["adjacency_transport"],
        }, path_trace)

    if module == "06":
        prefix = traffic_request["prefix"]
        allowed = control["policy"] == "ALLOW" and prefix == control["prefix"]
        programmed = trace["forwarding_programming"] == "PROGRAMMED"
        route = "FIB" if control["peer"] == "ESTABLISHED" and allowed and programmed else "FILTERED"
        healthy = control["peer"] == "ESTABLISHED" and allowed and route == "FIB"
        return _result(healthy, "BGP_PREFIX_FILTERED", {
            "session": control["peer"], "policy_action": control["policy"],
            "prefix": prefix, "rib_result": route,
            "forwarding_programming": trace["forwarding_programming"],
        }, path_trace)

    if module == "07":
        dns_ok = control["dns"] == traffic_request["expected_dns"] and trace["dns_path"] == "REACHABLE"
        lease_ok = control["dhcp"] == "enabled" and traffic_request["lease_address"] == "10.7.0.20" and trace["dhcp_path"] == "REACHABLE"
        ntp_offset = traffic_request["ntp_offset_ms"]
        syslog_ok = control["syslog"] == "enabled" and trace["syslog_path"] == "DELIVERED"
        healthy = dns_ok and lease_ok and abs(ntp_offset) < 100 and syslog_ok and control["ntp"] == traffic_request["expected_ntp"]
        return _result(healthy, "SERVICE_PLANE_DEGRADED", {
            "dns_ok": dns_ok, "lease_ok": lease_ok, "ntp_offset_ms": ntp_offset,
            "ntp_server": control["ntp"], "syslog_delivered": syslog_ok,
            "dns_path": trace["dns_path"], "dhcp_path": trace["dhcp_path"],
        }, path_trace)

    if module == "08":
        packet = traffic_request["packet"]
        decision = "UNDECIDED"
        if control["acl"] == "ALLOW-HTTPS" and packet["protocol"] == "tcp" and packet["port"] == 443 and trace["packet_path"] == "DELIVERED":
            decision = "ALLOW"
        healthy = decision == "ALLOW" and control["aaa"] == "REACHABLE" and control["secure_boot"] == "VALID"
        return _result(healthy, "POLICY_DENY", {
            "ordered_decision": decision, "aaa_server": control["aaa"],
            "boot_chain": control["secure_boot"], "packet": copy.deepcopy(packet),
            "packet_path": trace["packet_path"],
        }, path_trace)

    if module == "09":
        utilization = control["channel_utilization"]
        drops = traffic_request["queue_drops"] + (12 if trace["airtime_state"] == "SATURATED" else 0)
        healthy = (control["rssi"] > -70 and utilization < control["max_utilization"]
                   and traffic_request["packet_dscp"] == control["dscp"] and drops == 0)
        return _result(healthy, "AIRTIME_OR_QUEUE_CONGESTION", {
            "rssi": control["rssi"], "channel_utilization": utilization,
            "dscp": traffic_request["packet_dscp"], "drops": drops,
            "airtime_state": trace["airtime_state"],
        }, path_trace)

    if module == "10":
        rpf = control["rpf"] if trace["rpf_check"] == "PASS" else "uplink-b"
        healthy = (control["igmp"] == "joined" and control["pim"] == "FULL"
                   and rpf == "uplink-a" and traffic_request["healthy_backends"] > 0)
        return _result(healthy, "MULTICAST_RPF_FAILURE", {
            "igmp_membership": control["igmp"], "pim_neighbor": control["pim"],
            "rpf_interface": rpf, "healthy_backends": traffic_request["healthy_backends"],
            "rpf_check": trace["rpf_check"],
        }, path_trace)

    if module == "11":
        underlay = control["underlay"] == "reachable" and trace["underlay_reachability"] == "REACHABLE"
        type2 = traffic_request["remote_mac_count"] if control["evpn"] == "advertising" and underlay else 0
        bum = control["bum"] == "ingress-replication" and underlay
        healthy = underlay and control["vni"] == 5011 and type2 > 0 and bum
        return _result(healthy, "EVPN_MAC_ROUTE_MISSING", {
            "underlay_reachable": underlay, "vni": control["vni"],
            "evpn_type2_routes": type2, "bum_replication": bum,
            "underlay_reachability": trace["underlay_reachability"],
        }, path_trace)

    if module == "12":
        route = control["route"].split("->", 1)[-1]
        policy = control["policy"]
        listener = trace["backend_path"] == "REACHABLE"
        probe = route == "transit" and policy == "ALLOW" and listener and traffic_request["return_path"] == "transit"
        return _result(probe, "CLOUD_ROUTE_OR_POLICY_FAILURE", {
            "forwarding_next_hop": route, "policy_decision": policy,
            "backend_listener": listener, "return_path": traffic_request["return_path"],
            "backend_path": trace["backend_path"],
        }, path_trace)

    if module == "13":
        primary_up = control["primary_path"] == "up" and trace["private_path_state"] == "UP"
        selected = "private-a" if primary_up else "private-b"
        listener = traffic_request["service_listener_by_path"].get(selected, False)
        route = traffic_request["bgp_routes"].get("10.13.0.0/16")
        healthy = route == selected and listener and control["egress"] == "CONTROLLED" and control["bgp"] == "ESTABLISHED"
        return _result(healthy, "HYBRID_PATH_FAILOVER_REQUIRED", {
            "selected_route": route, "selected_path": selected,
            "service_listener": listener, "egress_policy": control["egress"],
            "private_path_state": trace["private_path_state"],
        }, path_trace)

    if module == "14":
        desired = control["state"]
        applied = trace["device_apply_state"] == "APPLIED"
        route = desired if applied else "route-deny"
        fib = "transit" if route == "route-allow" else "blackhole"
        probe = route == "route-allow" and fib == "transit"
        healthy = route == "route-allow" and fib == "transit" and probe and control["request_status"] == "ACCEPTED"
        return _result(healthy, "DRIFT_DEVICE_READBACK_MISMATCH", {
            "desired_route": desired, "device_route": route,
            "fib_next_hop": fib, "service_probe": probe,
            "device_apply_state": trace["device_apply_state"],
        }, path_trace)

    if module == "15":
        signals = copy.deepcopy(traffic_request["signals"])
        if control["telemetry_profile"] == "impaired" or trace["telemetry_transport"] == "PARTIAL":
            signals["timeline_complete"] = False
        healthy = (signals["metric_ms"] < 50 and signals["flow_status"] == 200
                   and signals["log_event"] == "ALLOW" and signals["timeline_complete"])
        return _result(healthy, "CORRELATED_SLO_BREACH", signals | {
            "telemetry_transport": trace["telemetry_transport"],
        }, path_trace)

    raise KeyError(f"unknown fixture module: {module}")


def evaluate(module: str, control: dict[str, Any], traffic_request: dict[str, Any], path_trace: dict[str, Any]) -> dict[str, Any]:
    return derive_dataplane(module, control, traffic_request, path_trace)


def evaluate_ownership(input_record: dict[str, Any]) -> dict[str, Any]:
    """Derive an owned-field assertion from effective state and raw trace."""
    readback = input_record["authoritative_readback"]
    request = input_record["fixture_request"]
    traffic_request = copy.deepcopy(input_record["traffic_request"])
    path_trace = copy.deepcopy(input_record["path_trace"])
    _assert_raw(traffic_request)
    _assert_raw(path_trace)
    effective = readback["effective_state"]
    derived = derive_dataplane(input_record["module"], effective["module_control"], traffic_request, path_trace)
    owned = effective["owned_field"]
    reconciliation = readback["reconciliation"]
    owned_field_applied = (owned.get("field_path") == request["requested_fields"]["field_path"] and owned.get("value") == "enabled")
    reconciled = (reconciliation["status"] in {"APPLIED", "NO_CHANGE"}
                  and readback["status"] == "ACTIVE" and request["status"] == "ACCEPTED"
                  and owned_field_applied and bool(reconciliation.get("change_record_id")))
    healthy = bool(reconciled and derived["healthy"])
    return {
        "healthy": healthy,
        "result": "HEALTHY" if healthy else "DATA_PLANE_ASSERTION_FAILED",
        "reconciliation_status": reconciliation["status"],
        "task_id": reconciliation["task_id"],
        "change_record_id": reconciliation["change_record_id"],
        "changed_fields": reconciliation["changed_fields"],
        "owned_field_applied": owned_field_applied,
        "owned_field_observed": copy.deepcopy(owned),
        "derived_probe": derived,
        "request_status": request["status"],
        "readback_status": readback["status"],
    }
